/**
 * Catálogo de poblaciones españolas con sus variantes de nombre.
 *
 * No pretende ser el callejero completo —España tiene más de 8.000 municipios—:
 * son las capitales de provincia y los municipios de mayor población, que
 * cubren la inmensa mayoría de las búsquedas. Lo que no esté sigue funcionando
 * por normalización (ver `resolver-municipio.ts`), sólo que sin nombre canónico
 * ni provincia automática.
 *
 * Los **alias** son la parte que de verdad arregla el buscador: el nombre
 * oficial de un municipio no suele ser el que la gente teclea. «Vila-real» se
 * busca como «Villarreal» o «Villareal», «Elx» como «Elche», «Donostia» como
 * «San Sebastián». Sin esta tabla, cada una de esas parejas es un comercio que
 * existe y no aparece.
 */

/** `[nombre canónico, provincia, ...variantes con las que se busca]`. */
type FilaMunicipio = readonly [string, string, ...string[]];

export interface Municipio {
  /** Cómo se escribe en las fichas y en los filtros. */
  readonly nombre: string;
  readonly provincia: string;
  /** Otras formas de escribirlo: oficial en otra lengua, castellanizada o errata frecuente. */
  readonly alias: readonly string[];
}

const FILAS: readonly FilaMunicipio[] = [
  // ── Capitales de provincia y grandes ciudades ──────────────────────────────
  ['Madrid', 'Madrid'],
  ['Barcelona', 'Barcelona'],
  ['Valencia', 'Valencia', 'València'],
  ['Sevilla', 'Sevilla'],
  ['Zaragoza', 'Zaragoza', 'Zaragosa'],
  ['Málaga', 'Málaga'],
  ['Murcia', 'Murcia'],
  ['Palma de Mallorca', 'Baleares', 'Palma'],
  ['Las Palmas de Gran Canaria', 'Las Palmas', 'Las Palmas'],
  ['Bilbao', 'Bizkaia', 'Bilbo'],
  ['Alicante', 'Alicante', 'Alacant'],
  ['Córdoba', 'Córdoba'],
  ['Valladolid', 'Valladolid'],
  ['Vigo', 'Pontevedra'],
  ['Gijón', 'Asturias', 'Xixón'],
  ['Vitoria-Gasteiz', 'Álava', 'Vitoria', 'Gasteiz'],
  ['A Coruña', 'A Coruña', 'La Coruña', 'Coruña'],
  ['Granada', 'Granada'],
  ['Elche', 'Alicante', 'Elx'],
  ['Oviedo', 'Asturias', 'Uviéu'],
  ['Badalona', 'Barcelona'],
  ['Cartagena', 'Murcia'],
  ['Terrassa', 'Barcelona', 'Tarrasa'],
  ['Jerez de la Frontera', 'Cádiz', 'Jerez'],
  ['Sabadell', 'Barcelona'],
  ['Santa Cruz de Tenerife', 'Santa Cruz de Tenerife', 'Santa Cruz'],
  ['Móstoles', 'Madrid'],
  ['Alcalá de Henares', 'Madrid'],
  ['Pamplona', 'Navarra', 'Iruña', 'Iruñea'],
  ['Fuenlabrada', 'Madrid'],
  ['Almería', 'Almería'],
  ['Leganés', 'Madrid'],
  ['San Sebastián', 'Gipuzkoa', 'Donostia', 'Donostia-San Sebastián'],
  ['Santander', 'Cantabria'],
  ['Castellón de la Plana', 'Castellón', 'Castellón', 'Castelló', 'Castelló de la Plana'],
  ['Burgos', 'Burgos'],
  ['Albacete', 'Albacete'],
  ['Getafe', 'Madrid'],
  ['Alcorcón', 'Madrid'],
  ['Logroño', 'La Rioja'],
  ['Salamanca', 'Salamanca'],
  ['Huelva', 'Huelva'],
  ['Marbella', 'Málaga'],
  ['Lleida', 'Lleida', 'Lérida'],
  ['Tarragona', 'Tarragona'],
  ['León', 'León'],
  ['Cádiz', 'Cádiz'],
  ['Jaén', 'Jaén'],
  ['Ourense', 'Ourense', 'Orense'],
  ['Girona', 'Girona', 'Gerona'],
  ['Lugo', 'Lugo'],
  ['Cáceres', 'Cáceres'],
  ['Melilla', 'Melilla'],
  ['Ceuta', 'Ceuta'],
  ['Guadalajara', 'Guadalajara'],
  ['Toledo', 'Toledo'],
  ['Pontevedra', 'Pontevedra'],
  ['Palencia', 'Palencia'],
  ['Ciudad Real', 'Ciudad Real'],
  ['Zamora', 'Zamora'],
  ['Ávila', 'Ávila'],
  ['Cuenca', 'Cuenca'],
  ['Huesca', 'Huesca', 'Osca'],
  ['Segovia', 'Segovia'],
  ['Soria', 'Soria'],
  ['Teruel', 'Teruel'],
  ['Badajoz', 'Badajoz'],
  ['Mérida', 'Badajoz'],

  // ── Área metropolitana de Madrid ───────────────────────────────────────────
  ['Alcobendas', 'Madrid'],
  ['Torrejón de Ardoz', 'Madrid', 'Torrejón'],
  ['Parla', 'Madrid'],
  ['Las Rozas de Madrid', 'Madrid', 'Las Rozas'],
  ['San Sebastián de los Reyes', 'Madrid', 'Sanse'],
  ['Pozuelo de Alarcón', 'Madrid', 'Pozuelo'],
  ['Coslada', 'Madrid'],
  ['Rivas-Vaciamadrid', 'Madrid', 'Rivas'],
  ['Valdemoro', 'Madrid'],
  ['Majadahonda', 'Madrid'],
  ['Collado Villalba', 'Madrid', 'Villalba'],
  ['Aranjuez', 'Madrid'],
  ['Arganda del Rey', 'Madrid', 'Arganda'],
  ['Boadilla del Monte', 'Madrid', 'Boadilla'],
  ['Pinto', 'Madrid'],
  ['Colmenar Viejo', 'Madrid'],
  ['Tres Cantos', 'Madrid'],
  ['San Fernando de Henares', 'Madrid'],
  ['Galapagar', 'Madrid'],
  ['Villaviciosa de Odón', 'Madrid'],

  // ── Cataluña ───────────────────────────────────────────────────────────────
  ["L'Hospitalet de Llobregat", 'Barcelona', 'Hospitalet de Llobregat', 'Hospitalet'],
  ['Mataró', 'Barcelona'],
  ['Santa Coloma de Gramenet', 'Barcelona', 'Santa Coloma'],
  ['Reus', 'Tarragona'],
  ['Sant Cugat del Vallès', 'Barcelona', 'Sant Cugat', 'San Cugat'],
  ['Cornellà de Llobregat', 'Barcelona', 'Cornellá', 'Cornella'],
  ['Sant Boi de Llobregat', 'Barcelona', 'Sant Boi', 'San Baudilio'],
  ['Manresa', 'Barcelona'],
  ['Rubí', 'Barcelona'],
  ['Vilanova i la Geltrú', 'Barcelona', 'Vilanova'],
  ['Viladecans', 'Barcelona'],
  ['Castelldefels', 'Barcelona'],
  ['Granollers', 'Barcelona'],
  ['Cerdanyola del Vallès', 'Barcelona', 'Cerdanyola'],
  ['Mollet del Vallès', 'Barcelona', 'Mollet'],
  ['Figueres', 'Girona', 'Figueras'],
  ['Blanes', 'Girona'],
  ['Lloret de Mar', 'Girona', 'Lloret'],
  ['Salou', 'Tarragona'],
  ['Sitges', 'Barcelona'],
  ['Vic', 'Barcelona', 'Vich'],
  ['Igualada', 'Barcelona'],

  // ── Comunidad Valenciana y Murcia ──────────────────────────────────────────
  ['Torrevieja', 'Alicante'],
  ['Orihuela', 'Alicante'],
  ['Torrent', 'Valencia', 'Torrente'],
  ['Gandía', 'Valencia', 'Gandia'],
  ['Benidorm', 'Alicante'],
  ['Paterna', 'Valencia'],
  ['Sagunto', 'Valencia', 'Sagunt'],
  ['Alcoy', 'Alicante', 'Alcoi'],
  ['Elda', 'Alicante'],
  ['San Vicente del Raspeig', 'Alicante', 'Sant Vicent del Raspeig', 'San Vicente'],
  ['Dénia', 'Alicante', 'Denia'],
  ['Vila-real', 'Castellón', 'Villarreal', 'Villareal', 'Villa-real', 'Vila real'],
  ['Alzira', 'Valencia', 'Alcira'],
  ['Xàtiva', 'Valencia', 'Játiva', 'Xativa'],
  ['Ontinyent', 'Valencia', 'Onteniente'],
  ['Borriana', 'Castellón', 'Burriana'],
  ['La Vall d’Uixó', 'Castellón', "Vall d'Uixó", 'Vall de Uxó'],
  ['Benicàssim', 'Castellón', 'Benicasim'],
  ['Vinaròs', 'Castellón', 'Vinaroz'],
  ['Oliva', 'Valencia'],
  ['Cullera', 'Valencia'],
  ['Manises', 'Valencia'],
  ['Mislata', 'Valencia'],
  ['Burjassot', 'Valencia', 'Burjasot'],
  ['Alboraya', 'Valencia', 'Alboraia'],
  ['Catarroja', 'Valencia'],
  ['Requena', 'Valencia'],
  ['Villena', 'Alicante'],
  ['Petrer', 'Alicante'],
  ['Novelda', 'Alicante'],
  ['Calpe', 'Alicante', 'Calp'],
  ['Xàbia', 'Alicante', 'Jávea', 'Javea'],
  ['Altea', 'Alicante'],
  ['La Vila Joiosa', 'Alicante', 'Villajoyosa'],
  ['Santa Pola', 'Alicante'],
  ['Lorca', 'Murcia'],
  ['Molina de Segura', 'Murcia', 'Molina'],
  ['Alcantarilla', 'Murcia'],
  ['Águilas', 'Murcia'],
  ['San Javier', 'Murcia'],
  ['Yecla', 'Murcia'],
  ['Mazarrón', 'Murcia'],
  ['Totana', 'Murcia'],
  ['San Pedro del Pinatar', 'Murcia'],

  // ── Andalucía ──────────────────────────────────────────────────────────────
  ['Dos Hermanas', 'Sevilla'],
  ['Algeciras', 'Cádiz'],
  ['Mijas', 'Málaga'],
  ['Fuengirola', 'Málaga'],
  ['Vélez-Málaga', 'Málaga', 'Vélez Málaga'],
  ['Estepona', 'Málaga'],
  ['Torremolinos', 'Málaga'],
  ['Benalmádena', 'Málaga'],
  ['Roquetas de Mar', 'Almería', 'Roquetas'],
  ['El Ejido', 'Almería'],
  ['Chiclana de la Frontera', 'Cádiz', 'Chiclana'],
  ['San Fernando', 'Cádiz'],
  ['El Puerto de Santa María', 'Cádiz', 'Puerto de Santa María'],
  ['Sanlúcar de Barrameda', 'Cádiz', 'Sanlúcar'],
  ['Utrera', 'Sevilla'],
  ['Alcalá de Guadaíra', 'Sevilla', 'Alcalá de Guadaira'],
  ['Motril', 'Granada'],
  ['Linares', 'Jaén'],
  ['Écija', 'Sevilla'],
  ['Antequera', 'Málaga'],
  ['Ronda', 'Málaga'],
  ['Úbeda', 'Jaén'],
  ['Puerto Real', 'Cádiz'],
  ['La Línea de la Concepción', 'Cádiz', 'La Línea'],
  ['Rincón de la Victoria', 'Málaga'],
  ['Nerja', 'Málaga'],
  ['Almuñécar', 'Granada'],
  ['Coín', 'Málaga'],
  ['Cártama', 'Málaga'],
  ['Lucena', 'Córdoba'],
  ['Puente Genil', 'Córdoba'],
  ['Andújar', 'Jaén'],
  ['Alcalá la Real', 'Jaén'],
  ['Almonte', 'Huelva'],
  ['Lepe', 'Huelva'],

  // ── Norte y resto ──────────────────────────────────────────────────────────
  ['Barakaldo', 'Bizkaia', 'Baracaldo'],
  ['Getxo', 'Bizkaia', 'Guecho'],
  ['Irún', 'Gipuzkoa', 'Irun'],
  ['Portugalete', 'Bizkaia'],
  ['Santurtzi', 'Bizkaia', 'Santurce'],
  ['Basauri', 'Bizkaia'],
  ['Errenteria', 'Gipuzkoa', 'Rentería'],
  ['Torrelavega', 'Cantabria'],
  ['Avilés', 'Asturias'],
  ['Siero', 'Asturias'],
  ['Langreo', 'Asturias'],
  ['Mieres', 'Asturias'],
  ['Ponferrada', 'León'],
  ['Miranda de Ebro', 'Burgos'],
  ['Aranda de Duero', 'Burgos'],
  ['Santiago de Compostela', 'A Coruña', 'Santiago'],
  ['Ferrol', 'A Coruña', 'El Ferrol'],
  ['Narón', 'A Coruña'],
  ['Vilagarcía de Arousa', 'Pontevedra', 'Villagarcía de Arosa'],
  ['Sanxenxo', 'Pontevedra', 'Sangenjo'],
  ['Tudela', 'Navarra'],
  ['Calahorra', 'La Rioja'],
  ['Barbastro', 'Huesca'],
  ['Jaca', 'Huesca'],
  ['Benavente', 'Zamora'],
  ['Medina del Campo', 'Valladolid'],
  ['Talavera de la Reina', 'Toledo', 'Talavera'],
  ['Puertollano', 'Ciudad Real'],
  ['Tomelloso', 'Ciudad Real'],
  ['Alcázar de San Juan', 'Ciudad Real', 'Alcázar'],
  ['Valdepeñas', 'Ciudad Real'],
  ['Plasencia', 'Cáceres'],
  ['Don Benito', 'Badajoz'],
  ['Almendralejo', 'Badajoz'],
  ['Villanueva de la Serena', 'Badajoz'],
  ['Getaria', 'Gipuzkoa', 'Guetaria'],
  ['Laredo', 'Cantabria'],
  ['Castro-Urdiales', 'Cantabria', 'Castro Urdiales'],

  // ── Islas ──────────────────────────────────────────────────────────────────
  ['Ibiza', 'Baleares', 'Eivissa'],
  ['Santa Eulalia del Río', 'Baleares', 'Santa Eulària des Riu'],
  ['Calvià', 'Baleares', 'Calviá'],
  ['Manacor', 'Baleares'],
  ['Inca', 'Baleares'],
  ['Mahón', 'Baleares', 'Maó'],
  ['Ciudadela', 'Baleares', 'Ciutadella', 'Ciutadella de Menorca'],
  ['Telde', 'Las Palmas'],
  ['Arrecife', 'Las Palmas'],
  ['Puerto del Rosario', 'Las Palmas'],
  ['San Bartolomé de Tirajana', 'Las Palmas', 'Maspalomas'],
  ['Arona', 'Santa Cruz de Tenerife'],
  ['Adeje', 'Santa Cruz de Tenerife'],
  ['San Cristóbal de La Laguna', 'Santa Cruz de Tenerife', 'La Laguna'],
  ['Los Cristianos', 'Santa Cruz de Tenerife'],
  ['Puerto de la Cruz', 'Santa Cruz de Tenerife'],
  ['Santa Lucía de Tirajana', 'Las Palmas'],
];

export const MUNICIPIOS_ES: readonly Municipio[] = FILAS.map(([nombre, provincia, ...alias]) => ({
  nombre, provincia, alias,
}));

/** Sólo los nombres, para los selectores que no necesitan más. */
export const CIUDADES_ES: readonly string[] = MUNICIPIOS_ES.map((m) => m.nombre);

export const PROVINCIAS_ES: readonly string[] = [
  'A Coruña', 'Álava', 'Albacete', 'Alicante', 'Almería', 'Asturias', 'Ávila',
  'Badajoz', 'Baleares', 'Barcelona', 'Burgos', 'Cáceres', 'Cádiz', 'Cantabria',
  'Castellón', 'Ceuta', 'Ciudad Real', 'Córdoba', 'Cuenca', 'Girona', 'Granada',
  'Guadalajara', 'Gipuzkoa', 'Huelva', 'Huesca', 'Jaén', 'La Rioja', 'Las Palmas',
  'León', 'Lleida', 'Lugo', 'Madrid', 'Málaga', 'Melilla', 'Murcia', 'Navarra',
  'Ourense', 'Palencia', 'Pontevedra', 'Salamanca', 'Santa Cruz de Tenerife',
  'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia',
  'Valladolid', 'Bizkaia', 'Zamora', 'Zaragoza',
];
